spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:49865;databaseName=SPCS_Adm_nikka;integratedSecurity=true;sendStringParametersAsUnicode=false;
    username: java
    password: java
  jpa:
    hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect

ekonomi:
  report:
    title: Kassaflöde
    template-path: D:\git\ekonomi\src\main\resources\se\montesmites\ekonomi\nikka\nikka-cashflow-report-definition.xml
    fiscal-year: 2019
    output-dir: C:\temp\nikka\reports\2019
