//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.23 at 10:18:08 AM CEST 
//


package se.montesmites.ekonomi.jaxb.model;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="regex" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;group ref="{se/montesmites/ekonomi/report-definition}account-group-post-processor" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "description",
        "regex",
        "accountGroupPostProcessor"
})
@XmlRootElement(name = "account-group")
public class AccountGroup {

    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected String regex;
    @XmlElement(name = "negate")
    protected List<Object> accountGroupPostProcessor;

    /**
     * Gets the value of the description property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the regex property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRegex() {
        return regex;
    }

    /**
     * Sets the value of the regex property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRegex(String value) {
        this.regex = value;
    }

    /**
     * Gets the value of the accountGroupPostProcessor property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accountGroupPostProcessor property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccountGroupPostProcessor().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     */
    public List<Object> getAccountGroupPostProcessor() {
        if (accountGroupPostProcessor == null) {
            accountGroupPostProcessor = new ArrayList<Object>();
        }
        return this.accountGroupPostProcessor;
    }

}
