//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.23 at 10:18:08 AM CEST 
//


package se.montesmites.ekonomi.jaxb.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the se.montesmites.ekonomi.jaxb.model package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: se.montesmites.ekonomi.jaxb.model
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Subtotal }
     */
    public Subtotal createSubtotal() {
        return new Subtotal();
    }

    /**
     * Create an instance of {@link Subtotal.Addenda }
     */
    public Subtotal.Addenda createSubtotalAddenda() {
        return new Subtotal.Addenda();
    }

    /**
     * Create an instance of {@link Report }
     */
    public Report createReport() {
        return new Report();
    }

    /**
     * Create an instance of {@link AccountGroups }
     */
    public AccountGroups createAccountGroups() {
        return new AccountGroups();
    }

    /**
     * Create an instance of {@link AccountGroup }
     */
    public AccountGroup createAccountGroup() {
        return new AccountGroup();
    }

    /**
     * Create an instance of {@link Section }
     */
    public Section createSection() {
        return new Section();
    }

    /**
     * Create an instance of {@link Body }
     */
    public Body createBody() {
        return new Body();
    }

    /**
     * Create an instance of {@link AccumulateAccountGroups }
     */
    public AccumulateAccountGroups createAccumulateAccountGroups() {
        return new AccumulateAccountGroups();
    }

    /**
     * Create an instance of {@link Definition }
     */
    public Definition createDefinition() {
        return new Definition();
    }

}
