//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.07.23 at 10:18:08 AM CEST
//

package se.montesmites.ekonomi.jaxb.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.*;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{se/montesmites/ekonomi/report-definition}report-constituent" maxOccurs="unbounded" minOccurs="0"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = {"reportConstituent"})
@XmlRootElement(name = "report")
public class Report {

  @XmlElements({
    @XmlElement(name = "account-groups", type = AccountGroups.class),
    @XmlElement(name = "subtotal", type = Subtotal.class),
    @XmlElement(name = "section", type = Section.class),
    @XmlElement(name = "accumulate-account-groups", type = AccumulateAccountGroups.class)
  })
  protected List<Object> reportConstituent;

  /**
   * Gets the value of the reportConstituent property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the reportConstituent property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getReportConstituent().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link AccountGroups } {@link
   * Subtotal } {@link Section } {@link AccumulateAccountGroups }
   */
  public List<Object> getReportConstituent() {
    if (reportConstituent == null) {
      reportConstituent = new ArrayList<Object>();
    }
    return this.reportConstituent;
  }
}
