//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.01 at 08:23:50 PM CEST 
//


package se.montesmites.ekonomi.jaxb.report_definition;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the se.montesmites.ekonomi.report_definition package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: se.montesmites.ekonomi.report_definition
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SectionRef }
     * 
     */
    public SectionRef createSectionRef() {
        return new SectionRef();
    }

    /**
     * Create an instance of {@link AccountGroupRef }
     * 
     */
    public AccountGroupRef createAccountGroupRef() {
        return new AccountGroupRef();
    }

    /**
     * Create an instance of {@link Report }
     * 
     */
    public Report createReport() {
        return new Report();
    }

    /**
     * Create an instance of {@link Section }
     *
     */
    public Section createSection() {
        return new Section();
    }

    /**
     * Create an instance of {@link AccountGroup }
     * 
     */
    public AccountGroup createAccountGroup() {
        return new AccountGroup();
    }

    /**
     * Create an instance of {@link SectionRef.CompactSection }
     * 
     */
    public SectionRef.CompactSection createSectionRefCompactSection() {
        return new SectionRef.CompactSection();
    }

    /**
     * Create an instance of {@link SectionRef.TotallingSection }
     * 
     */
    public SectionRef.TotallingSection createSectionRefTotallingSection() {
        return new SectionRef.TotallingSection();
    }

    /**
     * Create an instance of {@link SectionRef.NegatedSection }
     * 
     */
    public SectionRef.NegatedSection createSectionRefNegatedSection() {
        return new SectionRef.NegatedSection();
    }

    /**
     * Create an instance of {@link SectionRef.AccumulatingSection }
     * 
     */
    public SectionRef.AccumulatingSection createSectionRefAccumulatingSection() {
        return new SectionRef.AccumulatingSection();
    }

    /**
     * Create an instance of {@link Definition }
     * 
     */
    public Definition createDefinition() {
        return new Definition();
    }

}
